
services:
  - type: web
    name: milan-parking-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    rootDir: ./
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_MODE
        value: sandbox


